//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Acg_prefab
    {
        public const string BundleName = "acg_prefab";
        public const string ACG = "acg";
    }
    public class Bullet_prefab
    {
        public const string BundleName = "bullet_prefab";
        public const string BULLET = "bullet";
    }
    public class Endpanel_prefab
    {
        public const string BundleName = "endpanel_prefab";
        public const string ENDPANEL = "endpanel";
    }
    public class Enemy_prefab
    {
        public const string BundleName = "enemy_prefab";
        public const string ENEMY = "enemy";
    }
    public class Gamepad_prefab
    {
        public const string BundleName = "gamepad_prefab";
        public const string GAMEPAD = "gamepad";
    }
    public class Icon0_png
    {
        public const string BundleName = "icon0_png";
        public const string ICON0 = "icon0";
    }
    public class Icon1_png
    {
        public const string BundleName = "icon1_png";
        public const string ICON1 = "icon1";
    }
    public class Icon2_png
    {
        public const string BundleName = "icon2_png";
        public const string ICON2 = "icon2";
    }
    public class Icon3_png
    {
        public const string BundleName = "icon3_png";
        public const string ICON3 = "icon3";
    }
    public class Icon4_png
    {
        public const string BundleName = "icon4_png";
        public const string ICON4 = "icon4";
    }
    public class Icon5_png
    {
        public const string BundleName = "icon5_png";
        public const string ICON5 = "icon5";
    }
    public class Icon6_png
    {
        public const string BundleName = "icon6_png";
        public const string ICON6 = "icon6";
    }
    public class Icon7_png
    {
        public const string BundleName = "icon7_png";
        public const string ICON7 = "icon7";
    }
    public class Icon8_png
    {
        public const string BundleName = "icon8_png";
        public const string ICON8 = "icon8";
    }
    public class Icon9_png
    {
        public const string BundleName = "icon9_png";
        public const string ICON9 = "icon9";
    }
    public class Icon10_png
    {
        public const string BundleName = "icon10_png";
        public const string ICON10 = "icon10";
    }
    public class Icon11_png
    {
        public const string BundleName = "icon11_png";
        public const string ICON11 = "icon11";
    }
    public class Icon12_png
    {
        public const string BundleName = "icon12_png";
        public const string ICON12 = "icon12";
    }
    public class Icon13_png
    {
        public const string BundleName = "icon13_png";
        public const string ICON13 = "icon13";
    }
    public class Icon14_png
    {
        public const string BundleName = "icon14_png";
        public const string ICON14 = "icon14";
    }
    public class Icon15_png
    {
        public const string BundleName = "icon15_png";
        public const string ICON15 = "icon15";
    }
    public class Icon17_png
    {
        public const string BundleName = "icon17_png";
        public const string ICON17 = "icon17";
    }
    public class Icon18_png
    {
        public const string BundleName = "icon18_png";
        public const string ICON18 = "icon18";
    }
    public class Japancircle_prefab
    {
        public const string BundleName = "japancircle_prefab";
        public const string JAPANCIRCLE = "japancircle";
    }
    public class Japansquare_prefab
    {
        public const string BundleName = "japansquare_prefab";
        public const string JAPANSQUARE = "japansquare";
    }
    public class Playerstatepanel_prefab
    {
        public const string BundleName = "playerstatepanel_prefab";
        public const string PLAYERSTATEPANEL = "playerstatepanel";
    }
    public class Promptpanel_prefab
    {
        public const string BundleName = "promptpanel_prefab";
        public const string PROMPTPANEL = "promptpanel";
    }
    public class Ps_prefab
    {
        public const string BundleName = "ps_prefab";
        public const string PS = "ps";
    }
    public class Settlementobj_prefab
    {
        public const string BundleName = "settlementobj_prefab";
        public const string SETTLEMENTOBJ = "settlementobj";
    }
    public class Startpanel_prefab
    {
        public const string BundleName = "startpanel_prefab";
        public const string STARTPANEL = "startpanel";
    }
}
