//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class EndPanelData : QFramework.UIPanelData
    {
        public string title;
        public EndPanelData()
        {
            
        }

        public EndPanelData(string str)
        {
            title = str;
        }
    }
    
    public partial class EndPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as EndPanelData ?? new EndPanelData();
            // please add init code here
            txtPrompt.text = mData.title;
            
            btnExit.onClick.AddListener(() =>
            {
                Application.Quit();
            });
            btnRestart.onClick.AddListener(() =>
            {               
                SceneMgr.Instance.Load(1, () =>
                {
                    CoroutineMgr.Instance.StartCoroutine(openStatePanel());
                    UIKit.CloseAllPanel();
                });
            });
        }
        
        IEnumerator openStatePanel()
        {
            yield return new WaitForSeconds(0.5f);
            UIKit.OpenPanel<PlayerStatePanel>();

        }
        
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
