//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:cf88a780-53b4-43d9-bbc2-358cdcd9b4f6
    public partial class EndPanel
    {
        
        public const string NAME = "EndPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text txtPrompt;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnRestart;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnExit;
        
        private EndPanelData mPrivateData = null;
        
        public EndPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        EndPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new EndPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            txtPrompt = null;
            btnRestart = null;
            btnExit = null;
            mData = null;
        }
    }
}
