//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:7a836215-357e-4523-9c7f-7e6d1642f6e7
    public partial class PlayerStatePanel
    {
        
        public const string NAME = "PlayerStatePanel";
        
        [SerializeField()]
        public UnityEngine.UI.Image hpDeltaBar;
        
        [SerializeField()]
        public UnityEngine.UI.Image hpBar;
        
        [SerializeField()]
        public UnityEngine.UI.Text txtHp;
        
        [SerializeField()]
        public UnityEngine.UI.Image imgEquip;
        
        [SerializeField()]
        public UnityEngine.UI.Image imgEquipLife;
        
        private PlayerStatePanelData mPrivateData = null;
        
        public PlayerStatePanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        PlayerStatePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PlayerStatePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            hpDeltaBar = null;
            hpBar = null;
            txtHp = null;
            imgEquip = null;
            imgEquipLife = null;
            mData = null;
        }
    }
}
