//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class PromptPanelData : QFramework.UIPanelData
    {
        public EquipEnum equipA;
        public EquipEnum equipB;


        public PromptPanelData()
        {
            
        }
        public PromptPanelData(EquipEnum ea,EquipEnum eb)
        {
            equipA = ea;
            equipB = eb;
        }
    }
    
    public partial class PromptPanel : QFramework.UIPanel
    {
        private Image imgA;
        private Image imgB;
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as PromptPanelData ?? new PromptPanelData();
            // please add init code here
            imgA = transform.Find("imgA").GetComponent<Image>();
            imgB = transform.Find("imgB").GetComponent<Image>();
            
            btnA.gameObject.Find<Text>("Text").text = mData.equipA.ToString();
            btnB.gameObject.Find<Text>("Text").text = mData.equipB.ToString();

            btnA.onClick.AddListener(() =>
            {
               
                QMsgCenter.Instance.SendMsg(EventMsgPool.Instance.Allocate(
                    ((int)mData.equipA).ToString()
                    , (int) GameEventEnum.Skill.ChangeEquip
                ));
                Player.receiveInput = true;
                Time.timeScale = 1;
                CloseSelf();
            });
            btnB.onClick.AddListener(() =>
            {
                QMsgCenter.Instance.SendMsg(EventMsgPool.Instance.Allocate(
                    ((int)mData.equipB).ToString()
                    , (int) GameEventEnum.Skill.ChangeEquip
                ));
                Player.receiveInput = true;
                Time.timeScale = 1;
                CloseSelf();
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            mData = uiData as PromptPanelData ?? new PromptPanelData();
            imgA.sprite = ResourcesMgr.Instance.Get<Sprite>("icon/icon" + (int) mData.equipA);
            imgB.sprite = ResourcesMgr.Instance.Get<Sprite>("icon/icon" + (int) mData.equipB);
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
