//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:2368a468-191c-4ce0-81b3-40085d057b31
    public partial class PromptPanel
    {
        
        public const string NAME = "PromptPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button btnA;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnB;
        
        private PromptPanelData mPrivateData = null;
        
        public PromptPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        PromptPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PromptPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            btnA = null;
            btnB = null;
            mData = null;
        }
    }
}
