//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:a319431d-3ada-47df-9e06-725f085826d6
    public partial class StartPanel
    {
        
        public const string NAME = "StartPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button btnStart;
        
        [SerializeField()]
        public UnityEngine.UI.Button btnExit;
        
        private StartPanelData mPrivateData = null;
        
        public StartPanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        StartPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new StartPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            btnStart = null;
            btnExit = null;
            mData = null;
        }
    }
}
