//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UniRx;

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class StartPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class StartPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as StartPanelData ?? new StartPanelData();
            // please add init code here

            btnStart.OnClickAsObservable().Subscribe(_ =>
            {
                SceneMgr.Instance.Load(1, () =>
                {
                    UIKit.CloseAllPanel();
                    CoroutineMgr.Instance.StartCoroutine(openStatePanel());
                });
            });
            btnExit.OnClickAsObservable().Subscribe(_ =>
            {
                Application.Quit();
            });
        }

        IEnumerator openStatePanel()
        {
            yield return new WaitForSeconds(0.5f);
            UIKit.OpenPanel<PlayerStatePanel>();

        }
        
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
